<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="xunit" Version="2.9.0">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="coverlet.collector" Version="6.0.2">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Serilog" Version="4.0.1">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="RabbitMQ.Client" Version="6.8.1">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.6.0.1">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Moq" Version="4.20.72">
      <IncludeAssets>build</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Riok.Mapperly" Version="3.6.0">
      <IncludeAssets>compile; build; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.7.3">
      <IncludeAssets>compile; runtime</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
  </ItemGroup>
</Project>