version: '3.7'

services:

    backoffice:
        build: .
        hostname: backoffice
        restart: unless-stopped
        volumes:
            - ./Logs:/home/backoffice/logs:cached

networks:
    default:
        name: csharp_ddd_api_skeleton_network
        external: true