version: '3.7'

services:

    backend:
        build: 
            context: ..
            dockerfile: .devcontainer/Dockerfile
        hostname: backoffice
        ports:
            - 5004:8000
        volumes:
            - ..:/workspaces/backoffice:cached
        command: sleep infinity

networks:
    default:
        name: csharp_ddd_api_skeleton_network
        external: true